---
title: "732A90: Lab 3"
author: "David Björelind, davbj395"
date: "11/18/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
# Include packages here
library(poweRlaw)

```

## Question 1: Stable distribution

### 1.
```{r, echo=FALSE}

func = function(x, c){
  res = c/(sqrt(2*pi))*exp(-c^2/(2*x))*x^(-3/2)*1
  return(res)
}

power_func = function(x, alpha, tmin){
  res = c()
  for(i in 1:length(x)){
    ones = if(x[i] >= tmin) 1 else 0
    f = (alpha-1)/tmin*(x[i]/tmin)^(-alpha)* ones
    res = c(res, f)
  }
  return(res)
}

xgrid = seq(0, 200, length.out = 100)

c = 1
alpha = 2
tmin = 10
f_val = func(xgrid, c)
power_val = power_func(xgrid, alpha, tmin)

grid = seq(0.001, 200, length.out = 10000)
vals = func(grid, c)
pos = sum(vals[1:(10000/200)])/sum(vals) # Density between 0 to 1, meaning probability for value to occur there

plot(x = xgrid, y = f_val, type='l', col="black", ylab = "y-values", ylim=c(0, 0.05), main="f and fp")
lines(x = xgrid, y = power_val, type='l', col="red")

```
One problem is that the two functions has different support. The power-law is supported on (Tmin, inf) while f(x) has support on (0, inf). This means that support for (0, Tmin) is missing from power-law.

```{r, echo=FALSE}
#majorizing = function(y, tmin, alpha){
#  if (y<tmin){
#    return(density)
#  } else {
#    return(rplcon(n=1, xmin=tmin, alpha=alpha))
#  }
#}

```

### 2.
```{r, echo=FALSE}

acc_rej = function(tmin, alpha, p){
  while (1<2) {
    choice = rbinom(1,1,p)
    if (choice == 1){
      y = runif(1, 0,1)
      major_dens = power_func(y, alpha, tmin)
      c = 1
    } else{
      y = rplcon(n=1, xmin=tmin, alpha=alpha)
      major_dens = 1
      c = 1
    }
    # Different values for c
    u = runif(1, 0,1)
    if(u <= func(y)/(major_dens*c)){ # 1 if unif and f_power else
      return(y)
    }
  }
}

```
http://www.columbia.edu/~ks20/4703-Sigman/4703-07-Notes-ARM.pdf
### 3.
```{r, echo=FALSE}
# Generate a large sample
n_samples = 1000
rejects = 0 # Global variable to count number of rejections
for(i in 1:n_samples){
  
}

```

## Question 2: Laplace distribution

### 1.
```{r, echo=FALSE}

```

### 2. 
```{r}

```



## Another chunk
```{r}

```

## Another chunk
```{r}

```
### Include all code for this report
```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}
```